### ISSUE TITLE
Unable to follow the documentation to run smoothly.

### ISSUE THREAD

**Issue by dohooo** [nystudio107/vitejs-docker-dev#2] opened 2022-01-15 07:54 UTC
First of all, thank you for making this tool, can let me debug vite more easily and learn it. Thank you!

Maybe it's not a bug, but I want to give some feedback, because there may be people out there who have the same problem as me.

### Describe the bug

When I run 'make app-pnpm run build', I will be prompted with many type check errors by default, most of which are caused by the configuration problem of '/app/tsconfig.json' in the '/app' directory, which causes the incompatible vite module type check and causes the execution failure.

I recommend either removing `tsc` from build scripts or changing the default configuration in tsconfig.json so that it can at least run dev/build/serve.

### To reproduce
Steps to reproduce the behaviour:
1. Clone down _or_ download the `vitejs-docker-dev` repository:

Clone: `git clone https://github.com/nystudio107/vitejs-docker-dev.git`

Download: [vitejs-docker-dev](https://github.com/nystudio107/vitejs-docker-dev/archive/refs/heads/develop.zip)

2. Go into the `vitejs-docker-dev` directory:

```
cd vitejs-docker-dev
```

3. Build the Docker image:
```
make docker
```
This will be somewhat lengthy, as it builds the Docker image, and then clones down the [vitejs](https://github.com/vitejs/vite/) repository, and installs all of its dependencies

4. Start Vite in development mode (located in the `vite/` dir):
```
make vite-pnpm run dev
```

5. In a new terminal, start the Vite app that you use for developing/testing (located in the `app/` dir):
```
# build (important)
make app-pnpm run build
```

### Expected behaviour
works fine

### Screenshots
some types error from `/vitejs-docker-dev/vite/packages/vite/src`

### Versions
- Plugin version:
 - vitejs-docker-dev@1.0.3

**Comment by khalwat** [comment] 2022-01-15 16:53
hmmm that's pretty strange, the `app/` is just the default that is created using `vue-cli` to create a new TypeScript project.

It definitely was compiling properly when I created `vitejs-docker-dev` but I will attempt to reproduce.

**Comment by dohooo** [comment] 2022-01-15 16:57
Tomorrow I will try to reproduce this problem on another computer, perhaps because of my environment. I'll get back to you

**Comment by dohooo** [comment] 2022-01-15 16:57
> hmmm that's pretty strange, the `app/` is just the default that is created using `vue-cli` to create a new TypeScript project.
> 
> It definitely was compiling properly when I created `vitejs-docker-dev` but I will attempt to reproduce.

Thank you for your reply

**Comment by khalwat** [comment] 2022-01-15 16:58
Nope, shouldn't matter -- the point of using it in a Dockerized setup is that your local environment doesn't matter.

I'll try to reproduce it, and let you know.

**Comment by khalwat** [comment] 2022-01-15 18:12
I attempted to reproduce your issue, but I'm unable to.

I did the following:

1) Starting from a clean slate:

```
make clean
```

2) Building the Docker image:

```
make docker
```

3) Fire up Vite in development mode:

```
make vite-pnpm run dev
```

...and wait for the above to finish, until we see:
```
rollup v2.62.0
bundles /app/vite/packages/vite/src/client/env.ts → dist/client/env.mjs...
created dist/client/env.mjs in 7.2s
bundles /app/vite/packages/vite/src/client/client.ts → dist/client/client.mjs...
created dist/client/client.mjs in 6.5s
bundles /app/vite/packages/vite/src/node/index.ts, /app/vite/packages/vite/src/node/cli.ts → dist...
created dist in 29.2s

[2022-01-15 18:07:27] waiting for changes...
```

4) Wait for the above to finish, then fire up the app in a _new_ terminal window:

```
make app-pnpm run dev
```

...and wait until we see:
```

  vite v2.8.0-beta.2 dev server running at:

  > Local:    http://localhost:3000/
  > Network:  http://172.17.0.3:3000/

  ready in 3459ms.


```

Then I'm able to load the test app in the browser without issues:

<img width="1011" alt="Screen Shot 2022-01-15 at 1 43 21 PM" src="https://user-images.githubusercontent.com/7570798/149634068-de67e6d5-786f-4be3-a802-d88ff6f7d61a.png">

Nowhere in this process do I see any build errors. Can you show me what build errors you're seeing, and what you're doing to get them?

**Comment by khalwat** [comment] 2022-01-15 18:57
ahhhh my bad @dohooo -- you are saying it's the `build` that doesn't work for the app. Apologies for missing that detail, let me have a look.

**Comment by khalwat** [comment] 2022-01-15 19:03
Okay so the reason it fails is it runs `tsc` which checks the entire codebase using the `tsconfig.json` for the app, which is then applied to the entire Vite codebase, because it's all running in development mode.

I think the right thing to do here is just to remove the `tsc` and if people want to add that back in, it'll be up to them to resolve the type checking for their app to ensure it works with the rest of the Vite code base.

There probably isn't much of a use-case for building the app (the purpose of Vite.js Docker Dev is to help you develop Vite in a containerized way, not as a way for you to develop your own app.

But I agree it should work out of the box.

**Comment by khalwat** [comment] 2022-01-15 19:09
Addressed in: https://github.com/nystudio107/vitejs-docker-dev/commit/31d301d2246dd1064c9a5348e079507ec0ff42bf

Released as: https://github.com/nystudio107/vitejs-docker-dev/releases/tag/1.0.4

**Closed as completed by khalwat** 2022-01-15 19:09 UTC
Labels: bug

**Comment by dohooo** [comment] 2022-01-16 01:21
ahhhh, I thought I'd finally get a chance to submit PR to the library, but it looks like I didn't.

But thank you for checking anyway, okay

**Comment by khalwat** [comment] 2022-01-16 01:40
I'm sorry, you're right, I should have worked with you to get this PR integrated instead of doing it myself.

Apologies. Please don't let it discourage you from submitting future PRs!
